module Quickeebooks
  module Online
    module Model
      module AccountDetailType

        TYPES = %w(
          AccountsPayable
          AccountsReceivable
          AccumulatedAdjustment
          AccumulatedAmortization
          AccumulatedAmortizationOfOtherAssets
          AccumulatedDepletion
          AccumulatedDepreciation
          AdvertisingPromotional
          AllowanceForBadDebts
          Amortization
          Auto
          BadDebts
          BankCharges
          Buildings
          CashOnHand
          CharitableContributions
          Checking
          CommonStock
          CostOfLabor
          CostOfLaborCos
          CreditCard
          DepletableAssets
          Depreciation
          DevelopmentCosts
          DirectDepositPayable
          DiscountsRefundsGiven
          DividendIncome
          DuesSubscriptions
          EmployeeCashAdvances
          Entertainment
          EntertainmentMeals
          EquipmentRental
          EquipmentRentalCos
          FederalIncomeTaxPayable
          FurnitureAndFixtures
          Goodwill
          Insurance
          InsurancePayable
          IntangibleAssets
          InterestEarned
          InterestPaid
          Inventory
          Investment_MortgageRealEstateLoans
          Investment_Other
          Investment_TaxExemptSecurities
          Investment_USGovernmentObligations
          Land
          LeaseBuyout
          LeaseholdImprovements
          LegalProfessionalFees
          Licenses
          LineOfCredit
          LoanPayable
          LoansToOfficers
          LoansToOthers
          LoansToStockholders
          MachineryAndEquipment
          MoneyMarket
          NonProfitIncome
          NotesPayable
          OfficeGeneralAdministrativeExpenses
          OpeningBalanceEquity
          OrganizationalCosts
          OtherCostsOfServiceCos
          OtherCurrentAssets
          OtherCurrentLiabilities
          OtherFixedAssets
          OtherInvestmentIncome
          OtherLongTermAssets
          OtherLongTermLiabilities
          OtherMiscellaneousExpense
          OtherMiscellaneousIncome
          OtherMiscellaneousServiceCost
          OtherPrimaryIncome
          OwnersEquity
          PaidInCapitalOrSurplus
          PartnerContributions
          PartnerDistributions
          PartnersEquity
          PayrollClearing
          PayrollExpenses
          PayrollTaxPayable
          PenaltiesSettlements
          PreferredStock
          PrepaidExpenses
          PrepaidExpensesPayable
          PromotionalMeals
          RentOrLeaseOfBuildings
          RentsHeldInTrust
          RentsInTrustLiability
          RepairMaintenance
          Retainage
          RetainedEarnings
          SalesOfProductIncome
          SalesTaxPayable
          Savings
          SecurityDeposits
          ServiceFeeIncome
          ShareholderNotesPayable
          ShippingFreightDelivery
          ShippingFreightDeliveryCos
          StateLocalIncomeTaxPayable
          SuppliesMaterials
          SuppliesMaterialsCogs
          TaxesPaid
          TaxExemptInterest
          Travel
          TravelMeals
          TreasuryStock
          TrustAccounts
          TrustAccountsLiabilities
          UndepositedFunds
          Utilities
          Vehicles
        )

      end
    end
  end
end
